---
# tasks file for ansible-role-win-psexec
- name: Make sure extract directory exist
  win_file:
    path: '{{ ps_tools_extract_path }}'
    state: directory

- name: Download PSTools
  win_get_url:
    url: '{{ ps_tools_download_url }}'
    dest: '{{ ps_tools_extract_path }}\{{ ps_tools_filename_zip }}'
    force: no
    validate_certs: '{{ validate_certs | default(omit) }}'
    proxy_password: '{{ proxy_password | default(omit) }}'
    proxy_url : '{{ proxy_url  | default(omit) }}'
    proxy_use_default_credential: '{{ proxy_use_default_credential | default(omit) }}'
    proxy_username: '{{ proxy_username | default(omit) }}'

- name: Unzip PSTools
  win_unzip:
    src: '{{ ps_tools_extract_path }}\{{ ps_tools_filename_zip }}'
    dest: '{{ ps_tools_extract_path }}\'
    delete_archive: yes

- name: Copy psexec to install Path
  win_copy:
    remote_src: yes
    src: '{{ ps_tools_extract_path}}\{{ item }}'
    dest: '{{ ps_tools_install_path }}\{{ item }}'
  loop:
    - PsExec.exe
    - PsExec64.exe

- name: Remove extract directory
  win_file:
    path: '{{ ps_tools_extract_path }}'
    state: absent
  when: pstools_delete_extract_dir == true
